apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mahdi-website.fullname" . }}-web
  namespace: {{ include "mahdi-website.namespace" . }}
  labels:
    {{- include "mahdi-website.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mahdi-website.name" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mahdi-website.name" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if or .Values.imagePullSecret.create .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
          env:
            {{- range $key, $value := .Values.web.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mahdi-website.fullname" . }}-web
  namespace: {{ include "mahdi-website.namespace" . }}
  labels:
    {{- include "mahdi-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mahdi-website.name" . }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
