namespace:
  create: false
  name: mahdi-website

imagePullSecret:
  create: true
  name: mahdi-website-ghcr
  registry: ghcr.io
  username: "MahdiForoughi"
  password: ""
  email: "Dev.mahdi82@gmail.com"

web:
  replicaCount: 1
  image:
    repository: ghcr.io/foroughi/mahdi-website
    tag: ""
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  env:
    NODE_ENV : "production"
  resources: {}

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: mahdi.foroughi.cloud
      paths:
        - path: /
          pathType: Prefix
          service: web

  tls:
    - secretName: wildcard-foroughi-cloud-tls
      hosts:
        - mahdi.foroughi.cloud
